modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"
issueTrackerURL="https://github.com/CreaturesAndBeasts/Creatures_And_Beasts-Forge/issues"

[[mods]]
modId="creaturesandbeasts"
version="${mod_version}"
displayName="Creatures and Beasts"
# updateJSONURL="http://myurl.me/"
displayURL="https://github.com/CreaturesAndBeasts/Creatures_And_Beasts-Forge"
logoFile="logo.png"
credits="Credits to AzureDoom and Christian for contributions to the code"
authors="Joosh, CGessinger, HellionGames and BluSpring"
description='''
Creatures and Beasts is a vanilla-style creature mod which fills each biome with new mobs, from the plains of the overworld to the void of the end!
'''
[[dependencies.creaturesandbeasts]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creaturesandbeasts]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_forge}"
ordering="NONE"
side="BOTH"

[[dependencies.creaturesandbeasts]]
modId="geckolib"
mandatory=true
versionRange="[${geckolib_version},)"
ordering="BEFORE"
side="BOTH"

[[dependencies.creaturesandbeasts]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "BEFORE"
side = "BOTH"