# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G

# Project
maven_group = com.cgessinger.creaturesandbeasts
mod_version = 1.0.0
mod_id = cnb
mod_name = CreaturesAndBeasts

# Minecraft
minecraft_version = 26.1.2
supported_versions = 26.1.2

# Fabric
fabric_loader_version = 0.19.2
fabric_api_version = 0.149.1+26.1.2

# Dependencies
geckolib_version = 5.5.1
# https://maven.infernalstudios.org/releases/org/infernalstudios/config
infernalstudios_config_version = 4.0.3
# https://github.com/infernalstudios/Blazing-Config/blob/main/build.gradle
nightconfig_version = 3.6.4

# Publishing
publishing.curseforge = 1553289
publishing.modrinth = RQDFHc4w
